blank_issues_enabled: true
issue_templates:
  - name: "Post Comments"
    description: "Post issue for holding comments"
    title: "post/SLUG"
    labels: ["comment"]
    body: "./ISSUE_TEMPLATE/post_comments.md"
